[project]
name = "open"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "marimo>=0.18.4",
    "numpy>=2.4.0",
    "packaging>=25.0",
    "plotly>=6.5.0",
]
